import 'package:flutter/material.dart';

class CategoryUtils {
  static const Map<String, IconData> iconMap = {
    // Original mappings
    'shoppingBag': Icons.shopping_bag_outlined,
    'coffee': Icons.coffee_outlined,
    'car': Icons.directions_car_outlined,
    'home': Icons.home_outlined,
    'heart': Icons.favorite_outline,
    'smartphone': Icons.smartphone_outlined,
    'film': Icons.movie_outlined,
    'book': Icons.menu_book_outlined,
    'briefcase': Icons.work_outline,
    'gift': Icons.card_giftcard_outlined,
    'activity': Icons.show_chart,
    'plane': Icons.flight_outlined,
    'utensils': Icons.restaurant_outlined,

    // Default categories mappings from app_constants.dart
    'bus': Icons.directions_bus_outlined,
    'shopping-bag': Icons.shopping_bag_outlined, // duplicate name mapping
    'receipt': Icons.receipt_long_outlined,
    'gamepad-2': Icons.sports_esports_outlined,
    'heart-pulse': Icons.monitor_heart_outlined,
    'trending-up': Icons.trending_up_outlined,
    'graduation-cap': Icons.school_outlined,
    'sparkles': Icons.auto_awesome_outlined,
    'more-horizontal': Icons.more_horiz_outlined,

    // New additions for users to pick from
    'train': Icons.train_outlined,
    'local_taxi': Icons.local_taxi_outlined,
    'fastfood': Icons.fastfood_outlined,
    'local_cafe': Icons.local_cafe_outlined,
    'local_bar': Icons.local_bar_outlined,
    'kitchen': Icons.kitchen_outlined,
    'shopping_cart': Icons.shopping_cart_outlined,
    'checkroom': Icons.checkroom_outlined,
    'medical_services': Icons.medical_services_outlined,
    'pets': Icons.pets_outlined,
    'fitness_center': Icons.fitness_center_outlined,
    'pool': Icons.pool_outlined,
    'spa': Icons.spa_outlined,
    'palette': Icons.palette_outlined,
    'music_note': Icons.music_note_outlined,
    'mic': Icons.mic_outlined,
    'headphones': Icons.headphones_outlined,
    'computer': Icons.computer_outlined,
    'desktop_windows': Icons.desktop_windows_outlined,
    'chair': Icons.chair_outlined,
    'bed': Icons.bed_outlined,
    'cleaning_services': Icons.cleaning_services_outlined,
    'plumbing': Icons.plumbing_outlined,
    'water_drop': Icons.water_drop_outlined,
    'bolt': Icons.bolt_outlined,
    'wifi': Icons.wifi_outlined,
    'phone_in_talk': Icons.phone_in_talk_outlined,
    'build': Icons.build_outlined,
    'local_florist': Icons.local_florist_outlined,
    'grass': Icons.grass_outlined,
    'sports_soccer': Icons.sports_soccer_outlined,
    'sports_basketball': Icons.sports_basketball_outlined,
    'sports_tennis': Icons.sports_tennis_outlined,
    'directions_bike': Icons.directions_bike_outlined,
    'festival': Icons.festival_outlined,
    'park': Icons.park_outlined,
    'attractions': Icons.attractions_outlined,
    'flight_takeoff': Icons.flight_takeoff_outlined,
    'hotel': Icons.hotel_outlined,
    'luggage': Icons.luggage_outlined,
    'map': Icons.map_outlined,
    'monetization_on': Icons.monetization_on_outlined,
    'savings': Icons.savings_outlined,
    'account_balance': Icons.account_balance_outlined,
    'credit_card': Icons.credit_card_outlined,
    'account_balance_wallet': Icons.account_balance_wallet_outlined,
    'currency_exchange': Icons.currency_exchange_outlined,
    'child_care': Icons.child_care_outlined,
    'family_restroom': Icons.family_restroom_outlined,
    'stroller': Icons.stroller_outlined,
    'volunteer_activism': Icons.volunteer_activism_outlined,
    'handshake': Icons.handshake_outlined,
  };

  static IconData getIcon(String name) {
    return iconMap[name] ?? Icons.circle_outlined;
  }
}
